# Generated by Django 3.2.7 on 2021-09-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nfl_teams',
            fields=[
                ('team_name', models.CharField(max_length=420)),
                ('team_acronym', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='predicted_score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=420, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Hawk_Wk1', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk1', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk2', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk2', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk3', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk3', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk4', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk4', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk5', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk5', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk6', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk6', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk7', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk7', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk8', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk8', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk9', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk9', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk10', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk10', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk11', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk11', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk12', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk12', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk13', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk13', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk14', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk14', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk15', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk15', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk16', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk16', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk17', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk17', models.PositiveIntegerField(default=0, null=True)),
                ('Hawk_Wk18', models.PositiveIntegerField(default=0, null=True)),
                ('Opp_Wk18', models.PositiveIntegerField(default=0, null=True)),
                ('Submitted_Date', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_2021.nfl_teams')),
            ],
        ),
    ]
